const assert = require('assert')
const { When, Then } = require('@cucumber/cucumber')

// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')

let driver
let vars = {}

When('open the website',async function() {
  driver = await new Builder().forBrowser('firefox').build()
  await driver.get("https://onlinebanking.rhbgroup.com/my/login")
  await driver.findElement(By.css(".e1d8l7bt0 > .rhb-logo > svg")).click()
});

Then('I should find the landing page',async function () {
  assert(await driver.findElement(By.css(".css-1gbaytc-StyledBox-StyledFlex > svg")).getText() == "")
  await driver.quit()
});
