const assert = require('assert')
const { When, Then, Given } = require('@cucumber/cucumber')

// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')

let driver
let vars = {}

When('open the website',async function() {
  driver = await new Builder().forBrowser('firefox').build()
  await driver.get("https://merchantdashboard.pdg.midf.com.my")
});

Then('I should find the landing page',async function () {
  //assert(await driver.findElement(By.xpath("/html/body/div[1]/div/div/h1")).getText() == "Bank Logo")
  await driver.quit()
});

Given('I logged in as admin',async function () {
  driver = await new Builder().forBrowser('firefox').build()
  await driver.get("https://merchantdashboard.pdg.midf.com.my")
  await driver.sleep(5000)
  //await driver.findElement(By.name("username")).sendKeys("admin")
  await driver.findElement(By.name("username")).sendKeys("pocuser1.qbistro@demo.com")
  await driver.findElement(By.name("password")).sendKeys("Password@12345")
  await driver.findElement(By.css(".mt-4")).click()
  //await driver.findElement(By.name("Login")).click()
});


When('I clicked about button',async function () {
  await driver.findElement(By.linkText("About")).click()
});

Then('I should find the dvwa landing page',async function () {
  const elements = await driver.findElements(By.css("#header > img"))
  assert(elements.length)
  await driver.quit()
});
