const assert = require('assert')
const { When, Then, Given, setDefaultTimeout } = require('@cucumber/cucumber')

// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')

let driver
let vars = {}
setDefaultTimeout(60 * 1000);

When('open the website',async function() {
  driver = await new Builder().forBrowser('firefox').build()
  await driver.get("https://merchantdashboard.pdg.midf.com.my")
});

Then('I should find the landing page',async function () {
  await driver.sleep(3000)
  assert(await driver.findElement(By.name('username')))
  await driver.quit()
});

Given('I logged in as admin',async function () {
  driver = await new Builder().forBrowser('firefox').build()
  await driver.get("https://merchantdashboard.pdg.midf.com.my")
  await driver.sleep(3000)
  await driver.findElement(By.name("username")).sendKeys("pocuser1.qbistro@demo.com")
  await driver.findElement(By.name("password")).sendKeys("Password@12345")
  await driver.findElement(By.css(".mt-4")).click()
});

Then('I should see dashboard',async function () {
  await driver.sleep(6000)
  let elements = await driver.findElements(By.css(".rounded-2xl > .text-sm"))
  //assert (elements.length > 0, "The length of the elements should be larger than 0")
  assert (elements.length)
  await driver.quit()
});
